### ISSUE TITLE
Updates to complete

### ISSUE THREAD

**Issue by alexandrarh** [alexavndra/battery-cycle-data-viz#1]
~~Update the README.md because it's a web app now lmao~~

**Comment by alexandrarh** [comment]
~~Update instructions #2 on the website~~

**Comment by alexandrarh** [comment]
~~- Fix spacing on heading sentence~~

**Comment by alexavndra** [comment]
Add "save" button to download visualization (no need to do any right clicking)

**Comment by alexavndra** [comment]
Write part where you can do raw NDA files (need to change the formatting)

**Comment by alexandrarh** [comment]
~~Read xls to csv (.read_excel(sheet_name="Records")) or something~~

**Comment by alexandrarh** [comment]
~~If generating certain cycles, have a way to return .csv file containing only those cycles~~

**Comment by alexandrarh** [comment]
Finished!
